### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by quanru** [obsidianmd/obsidian-translations#972]
![image](https://github.com/obsidianmd/obsidian-translations/assets/11739753/9f144197-c984-4574-b4f3-7c1da3a3ea65)
![image](https://github.com/obsidianmd/obsidian-translations/assets/11739753/f4847a19-6506-4b47-a5dd-2c1724100471)
Should be translated into『仅显示已安装的主题』

**Comment by quanru** [comment]
yes

**Comment by jangaza** [comment]
done, thanks for notifying

**Comment by Acylation** [comment]
额搞不明白之前翻译了好多，现在 `1.6.1` 版本还没有实装，请问应该向这个仓库提 issue 还是找到中文翻译仓库？

When will the updated zh.json deployed? I can still see some missing translations in the insider version `1.6.1` though I've translated and the PR was merged for these.

![image](https://github.com/obsidianmd/obsidian-translations/assets/73122375/c4a57edb-5b6d-4f0d-90b6-3b0e2f7aae0c)

**Comment by joethei** [comment]
We normally update the translations with the first public build.

**Comment by joethei** [comment]
Translations have been updated in the latest build.
